package main

import (
	_ "embed"
	"encoding/base64"
)

//go:embed index.html
var indexhtmlBytes []byte

//go:embed markhtml.min.js
var markhtmlJSBytes []byte

//go:embed markhtml.css
var markhtmlCSSBytes []byte

var IcoFile = "AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA/4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAERERABAAAAAQAAEAEAAAABAAAQAQAAAAEAABABAAAAAQAREAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEREREBEREQAQAAAQAAAAABAAABAAAAAAEAAAEAAAAAAQAAAQAAAAABAAABAAAAAAEAAAEAAAAAAREREQAAAAC/gQAAv70AAL+9AAC/vQAAv7EAAL+/AAC/vwAAv78AAICBAAC+/wAAvv8AAL7/AAC+/wAAvv8AAL7/AACA/wAA"

var (
	icoFileBytes []byte
)

func init() {
	var err error
	icoFileBytes, err = base64.StdEncoding.DecodeString(IcoFile)
	if err != nil {
		panic(err)
	}
}
